
import javax.swing.JOptionPane;

public class PilhaDinamicaUI extends javax.swing.JFrame {

    Pilha<Integer> pInt;
    Pilha<String> pStr;
    
    public PilhaDinamicaUI() {
        initComponents();
        
        pInt = new Pilha();
        pStr = new Pilha();
        
        //Agrupar rdobuttons
        rdogroupTipoPilha.add(rdoInt);
        rdogroupTipoPilha.add(rdoString);
        rdoInt.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdogroupTipoPilha = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rdoInt = new javax.swing.JRadioButton();
        rdoString = new javax.swing.JRadioButton();
        pnlPush = new javax.swing.JPanel();
        lblEmpilhar = new javax.swing.JLabel();
        txtEmpilhar = new javax.swing.JTextField();
        btnEmpilhar = new javax.swing.JButton();
        pnlPop = new javax.swing.JPanel();
        lblDesempilhar = new javax.swing.JLabel();
        btnDesempilhar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPilhaAtual = new javax.swing.JTextArea();
        lblTamanho = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pilha Dinâmica");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tipo da Pilha"));

        rdoInt.setText("Inteiros");
        rdoInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoIntActionPerformed(evt);
            }
        });

        rdoString.setText("Texto");
        rdoString.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoStringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rdoInt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoString)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoInt)
                    .addComponent(rdoString))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPush.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Push"));

        lblEmpilhar.setText("Inserir elemento na pilha:");

        btnEmpilhar.setText("Empilhar");
        btnEmpilhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpilharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPushLayout = new javax.swing.GroupLayout(pnlPush);
        pnlPush.setLayout(pnlPushLayout);
        pnlPushLayout.setHorizontalGroup(
            pnlPushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPushLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlPushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEmpilhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEmpilhar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpilhar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPushLayout.setVerticalGroup(
            pnlPushLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPushLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEmpilhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmpilhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmpilhar)
                .addContainerGap())
        );

        pnlPop.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pop"));

        lblDesempilhar.setText("Remover elemento da pilha");

        btnDesempilhar.setText("Desempilhar");
        btnDesempilhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesempilharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPopLayout = new javax.swing.GroupLayout(pnlPop);
        pnlPop.setLayout(pnlPopLayout);
        pnlPopLayout.setHorizontalGroup(
            pnlPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDesempilhar)
                    .addComponent(btnDesempilhar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPopLayout.setVerticalGroup(
            pnlPopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDesempilhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDesempilhar)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Pilha atual"));

        txtPilhaAtual.setColumns(1);
        txtPilhaAtual.setRows(5);
        jScrollPane1.setViewportView(txtPilhaAtual);

        lblTamanho.setText("A pilha possui 0 elementos.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblTamanho)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTamanho)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPush, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlPop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPush, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlPop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpilharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpilharActionPerformed
        if (rdoInt.isSelected()) {
            int valor = Integer.parseInt(txtEmpilhar.getText());
            pInt.push(valor);
            txtPilhaAtual.setText(pInt.imprime());
            lblTamanho.setText("A pilha Int possui " + pInt.size() + " elementos.");
            
        } else if (rdoString.isSelected()) {
            String valor = txtEmpilhar.getText();
            pStr.push(valor);
            txtPilhaAtual.setText(pStr.imprime());
            lblTamanho.setText("A pilha Str possui " + pStr.size() + " elementos.");
        }
        txtEmpilhar.setText("");
        txtEmpilhar.grabFocus();
    }//GEN-LAST:event_btnEmpilharActionPerformed

    private void rdoIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoIntActionPerformed
        txtPilhaAtual.setText(pInt.imprime());
        lblTamanho.setText("A pilha Int possui " + pInt.size() + " elementos.");
    }//GEN-LAST:event_rdoIntActionPerformed

    private void rdoStringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoStringActionPerformed
        txtPilhaAtual.setText(pStr.imprime());
        lblTamanho.setText("A pilha Str possui " + pStr.size() + " elementos.");
    }//GEN-LAST:event_rdoStringActionPerformed

    private void btnDesempilharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesempilharActionPerformed
        if (rdoInt.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Elemento " + pInt.pop() + " desempilhado!");
            txtPilhaAtual.setText(pInt.imprime());
            lblTamanho.setText("A pilha Int possui " + pInt.size() + " elementos.");
        } else if (rdoString.isSelected()) {
            JOptionPane.showMessageDialog(rootPane, "Elemento " + pStr.pop() + " desempilhado!");
            txtPilhaAtual.setText(pStr.imprime());
            lblTamanho.setText("A pilha Str possui " + pStr.size() + " elementos.");
        }
    }//GEN-LAST:event_btnDesempilharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PilhaDinamicaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PilhaDinamicaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PilhaDinamicaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PilhaDinamicaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PilhaDinamicaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDesempilhar;
    private javax.swing.JButton btnEmpilhar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesempilhar;
    private javax.swing.JLabel lblEmpilhar;
    private javax.swing.JLabel lblTamanho;
    private javax.swing.JPanel pnlPop;
    private javax.swing.JPanel pnlPush;
    private javax.swing.JRadioButton rdoInt;
    private javax.swing.JRadioButton rdoString;
    private javax.swing.ButtonGroup rdogroupTipoPilha;
    private javax.swing.JTextField txtEmpilhar;
    private javax.swing.JTextArea txtPilhaAtual;
    // End of variables declaration//GEN-END:variables
}
